### PR TITLE
vgmdb_importer: Fix bugs and other problems

### LINKED ISSUE #361: [BUG] VGMDb importer keeps importing the day at the 4th
The VGMDb importer keeps importing the day at the 4th. Looking back, I’ve got a whole bunch of releases I’ve added with the correct year and month, but the date is the 4th on all of them.

Using with Safari/[Tampermonkey](https://www.tampermonkey.net/).

### LINKED ISSUE #375: VGMdb importer presents Amazon links as purchase for relationships instead of AISN relationship
The VGMdb importer presents Amazon links as one of the purchase for relationships instead of AISN relationship.

### PR DESCRIPTION
**Pull request by augustjanse**
Turns out `getDay()` returns weekday. Whoops! And also we should use UTC dates.

Fixes #361. Fixes #375.

### CODE REVIEW

**Comment by augustjanse** [comment]
Thanks for merging #372. I might as well fix #375 before you merge this one.

**Comment by augustjanse** [comment]
I was of the impression that most links were to mail-order stores because that's probably the kind of releases I used to edit, but I see now that that's not a great assumption, so I removed that and mapped a few common store names. Fixes #375.

**Comment by JuniorJPDJ** [comment]
Would be cool to fix lint warnings before merge.

**Comment by augustjanse** [comment]
@JuniorJPDJ These two?

```
/home/runner/work/musicbrainz-userscripts/musicbrainz-userscripts/vgmdb_importer.user.js
Warning:   132:18  warning  'linkType' is not defined  no-undef
Warning:   135:64  warning  'linkType' is not defined  no-undef
```

I'll do that, thanks.

**Comment by augustjanse** [comment]
@JuniorJPDJ That should have done it.

**Comment by murdos** [comment]
@augustjanse : is this ready? could I merge it?

**Comment by augustjanse** [comment]
@murdos It's ready!

**Comment by murdos** [comment]
Thanks @augustjanse !

**Pull request merged**
